version: '3'

services:
  app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:7

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root